# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

XCODEPROJ = "../Marvel.xcodeproj"
XCWORKSPACE = "../Marvel.xcworkspace"
TEST_SCHEME = "Marvel"
RELEASE_SCHEME = "Release"


  lane :test do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
    ENV["XCPRETTY_JSON_FILE_OUTPUT"] = "fastlane/test_output/summary.json"
    cocoapods
    begin
      sh "slather coverage -s --scheme Marvel --workspace #{XCWORKSPACE} #{XCODEPROJ}"
    rescue => ex
      UI.error("Something went wrong: #{ex}")
    end
  end 